version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - POSTGRES_DB=app_db
